name: Java CI Tests

on:
  push:
    # Запускаем тесты при пуше во все ветки
    branches: [ "**" ]
  pull_request:
    # Обязательно запускаем тесты внутри PR, чтобы работала защита веток
    branches: [ "main", "develop" ]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Tests with Gradle
        run: |
          chmod +x gradlew
          ./gradlew test
