name: Development CI

on:
  push:
    branches: [ "develop", ["main"], "**" ]
  pull_request:
    branches: [ "develop", ["main"], "**" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Tests with Gradle
        run: |
          chmod +x gradlew
          ./gradlew test

      - name: Build JAR Game Artifact
        run: ./gradlew build -x test

      - name: Upload Game Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: roguelike-game-build
          path: build/libs/*.jar
